projects:
  awsblog:
    schemaPath: src/graphql/schema.json
    includes:
      - awsblog
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
